#!/bin/bash

#executar como ./perfctr <core> <grupo> <passo> <inicio> <fim>
#executa o programa matmult com matrizes de tamanho <inicio> até <fim> com passo <passo>
#Deve-se passar o core a ser utilizado e indicador na linha de comando (L2CACHE, L3, FLOPS_DP e FLOPS_AVX)
#o resultado é um arquivo com 4 colunas: ordem da matriz/vetor, resultados do indicador para cada uma 
#das 3 funções

LIKWID_CMD="likwid-perfctr -C $1 -g $2 -m -O"

cache="L2 miss ratio"
cachebw="L3 bandwidth"
flopsDP="Scalar MUOPS/s"
flopsAVX="packed MUOPS/s"

passo="$3"
inicio="$4"
fim="$5"

#shift 2

#${LIKWID_CMD} $*

#modprobe msr

#export PATH=/home/soft/likwid/bin:/home/soft/likwid/sbin:$PATH
#export LD_LIBRARY_PATH=/home/soft/likwid/lib:$LD_LIBRARY_PATH

# Para obter lista de grupos de indicadores de performance:
#      likwid-perfctr -a

# Para obter topologia dos processadores
#      likwid-topology -c -g

#---Confere se a opçao é FLOPS_AVX. Se for, complia com a opçao -o3---
if [ "$2" == "FLOPS_AVX" ]
then
	make avx
else
	make
fi

#---Confere os indicadores e salva o padrao que procuramos em cada um---
if [ "$2" == "L2CACHE" ]
then
	padrao="$cache"
elif [ "$2" == "L3" ]
then
	padrao="$cachebw"
elif [ "$2" == "FLOPS_DP" ]
then
	padrao="$flopsDP"
else
	padrao="$flopsAVX"
fi
#-----------------------------------------------------------------------

while [ "$inicio" -le "$fim" ]
do
	${LIKWID_CMD} ./matmult -n $inicio > temp.tmp

	printf "$((inicio*inicio*8)) "
	printf "$(grep "$padrao" temp.tmp | awk -F"," '{print $2}' | tr "\n" " ")\n"

	(( inicio += "$passo" ))

done > $2.tmp

#-----------------------------------------------------------------------
#----------------gnuplot para fazer os graficos-------------------------
gnuplot <<- EOF
	set logscale x
	set xlabel "N (bytes)"
	set ylabel "$escolha"
	set title "Medição de performance para $2"   
	set style data point
	set style function line

	set style line 1 lc rgb "red" lw 2
	set style line 2 lc rgb "orange" lw 2
	set style line 3 lc rgb "green" lw 2

	set term png
	set output "$2.png"
	plot "$2.tmp" using 1:2 ls 1 title 'multMatPtrVet' with lines, \
	"$2.tmp" using 1:3 ls 2 title 'multMatRowVet' with lines, \
	"$2.tmp" using 1:4 ls 3 title 'multMatColVet' with lines
EOF

rm *.tmp
make purge


